### ISSUE TITLE
Get 403 Forbidden error when connecting to docker socket proxy

### ISSUE THREAD

**Issue by ldy5413** [nextcloud/app_api#329]
I am trying to add the appapi in my nextcloud AIO but after enable the Docker Socket Proxy in master container, I cannot connect to it, the error message is like below

ClientException
Client error: `GET http://nextcloud-aio-docker-socket-proxy:2375/v1.41/_ping` resulted in a `403 Forbidden` response: <html><body><h1>403 Forbidden</h1> Request forbidden by administrative rules. </body></html>
Could not connect to Docker daemon

**Comment by andrey18106** [comment]
Hi, @ldy5413!

What version of the Nextcloud AIO are you using? Is there any specific changes of configuration?

**Comment by ldy5413** [comment]
> Hi, @ldy5413!
> 
> What version of the Nextcloud AIO are you using? Is there any specific changes of configuration?

Hi @andrey18106 , my AIO version is 29.0.3, I host it locally and use a nginx reverse proxy before it. Then there should be no other specific changes of configuration.

**Comment by ldy5413** [comment]
> > Hi, [@ldy5413](https://github.com/ldy5413)!
> > What version of the Nextcloud AIO are you using? Is there any specific changes of configuration?
> 
> Hi [@andrey18106](https://github.com/andrey18106) , my AIO version is 29.0.3, I host it locally and use a nginx reverse proxy before it. Then there should be no other specific changes of configuration.

This issue disappeared after an update
