### ISSUE TITLE
Tutorial for simple app and development process

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/app_api#392]
It would be great to have a very simple tutorial teaching how one can start ext app development. Not necessarily needing details on how to implement specific functionality but more about:

- how to I get a local dev setup
- how can I install, run, do changes and rerun the new app from my local git repository 
- how can I debug communication between the external app and nextcloud
- what are the minimum requirements for an ext app, like a hello world

**Comment by edward-ly** [comment]
@juliushaertl First tutorial is now out. If it looks good to you, you can close this issue.

https://help.nextcloud.com/t/new-tutorial-develop-your-first-exapp-in-python/205108

**Comment by juliushaertl** [comment]
That looks great, thank you very much for that ❤
