### ISSUE TITLE
Migration of documentation to Nextcloud documentation

### ISSUE THREAD

**Issue by bigcat88** [nextcloud/app_api#415]
**Task: Migrate and Refactor AppAPI Documentation for Nextcloud**

**Context:** 
We cannot make significant updates to our current AppAPI documentation because the more we update it now, the more we’ll have to redo later. Additionally, much of the old documentation was written before AppAPI became a built-in application. At that time, the documentation was simpler, as we assumed users knew why they were installing AppAPI and how to configure it.

Now that AppAPI is a built-in application, the documentation requirements have changed, necessitating this migration and refactor to better suit the new user base.

We need to migrate the current documentation from [AppAPI's GitHub Pages](https://nextcloud.github.io/app_api/) to the official Nextcloud documentation, located [here](https://docs.nextcloud.com), and split it into two sections:

1. **Admin Documentation**: Content related to administration should go to the Nextcloud Admin Docs.
2. **Development Documentation**: Content related to development should be moved to the development manual, specifically the section on developing ExApps.

Each section should also have its own FAQ, which we'll review and complete later.

As part of this migration, the main tasks include:
1. Reread the entire documentation and remove outdated content.
2. Divide it into two parts: Admin and Development.
3. Rework the **Table of Contents** for each part to make it easier to find relevant sections and to reference from the AppAPI UI.
4. Add missing sections such as a detailed FAQ and more configuration examples where necessary.
5. Submit it for review, then merge it into the main Nextcloud documentation.

Remember, the documentation doesn't need to be perfect in this iteration; it just needs to be split and structured.
This is for **Nextcloud version 30+** only, and it's important to reflect that AppAPI is now an embedded application.

**Even draft PRs are acceptable, as long as we have a foundation to move forward.**

**Comment by DaphneMuller** [comment]
Clarification on what is outdated content: a lot of content was written before AppAPI was a shipped app. Content that makes no longer sense due to this change, should be removed.

**Comment by bigcat88** [comment]
A new PR has been created for the Flow repository (https://github.com/nextcloud/flow/pull/14) with two `todo`' in it with links to the Nextcloud docs (file: README.md).

It would be nice to include this information in future documentation so that when it appears we can update the necessary links in the Flow repository.

@edward-ly

**Comment by edward-ly** [comment]
Sorry for the wait, but I think I am satisfied now in terms of the top-level reorganizing the existing documentation. I still need another pass to re-read the documentation again for outdated info, though, maybe re-order some pieces here and there too if needed. If you think it's ready to merge right now, let me know and I can mark it as such.

> A new PR has been created for the Flow repository ([nextcloud/flow#14](https://github.com/nextcloud/flow/pull/14)) with two `todo`' in it with links to the Nextcloud docs (file: README.md).
> 
> It would be nice to include this information in future documentation so that when it appears we can update the necessary links in the Flow repository.

For the info in both links, I'm not sure how much of it is tied to the fact that Flow is a Python app. For Python-specific info, I'm not sure how much of it would be appropriate for inclusion in the documentation. Maybe linking [the tutorial](https://cloud.nextcloud.com/s/iyNGp8ryWxc7Efa?path=%2F8%20Develop%20your%20first%20ExApp%20in%20Python) would be sufficient?

**Comment by edward-ly** [comment]
> I still need another pass to re-read the documentation again for outdated info, though, maybe re-order some pieces here and there too if needed. If you think it's ready to merge right now, let me know and I can mark it as such.

Second pass is done and PR is now marked as ready. There are probably some things that I still missed, but you can let me know if you want to address them now or later.

**Comment by edward-ly** [comment]
Final pass is now done and PR is merged.
